food = ["Hamburger", "Hot Dog", "Pizza", "Funnel Cake", "Donut", "Wings"]
print(sorted(food))
print(sorted(food, reverse=True))
food.append("Sandwich")
print(food)
food.insert(1, "Ice Cream")
print(food)
del food[2]
print(food)
food.pop(1)
print(food)
food.remove("Hamburger")
print(food)
food.sort()
print(food)
food.sort(reverse=True)
print(food)
food.reverse()
print(food)
print(len(food))
